# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'State.ui'
#
# Created: Mon Mar 16 17:47:55 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(582, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"font: 8pt \"Arial\";")
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 371, 301))
        self.groupBox.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.splitter_27 = QtGui.QSplitter(self.groupBox)
        self.splitter_27.setGeometry(QtCore.QRect(10, 10, 310, 250))
        self.splitter_27.setMinimumSize(QtCore.QSize(224, 174))
        self.splitter_27.setOrientation(QtCore.Qt.Vertical)
        self.splitter_27.setObjectName("splitter_27")
        self.splitter = QtGui.QSplitter(self.splitter_27)
        self.splitter.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.CaseNumberLabel = QtGui.QLabel(self.splitter)
        self.CaseNumberLabel.setObjectName("CaseNumberLabel")
        self.CaseNumber = QtGui.QLineEdit(self.splitter)
        self.CaseNumber.setMinimumSize(QtCore.QSize(148, 15))
        self.CaseNumber.setObjectName("CaseNumber")
        self.splitter_6 = QtGui.QSplitter(self.splitter_27)
        self.splitter_6.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.AnimalNameLabel = QtGui.QLabel(self.splitter_6)
        self.AnimalNameLabel.setObjectName("AnimalNameLabel")
        self.AnimalName = QtGui.QLineEdit(self.splitter_6)
        self.AnimalName.setMinimumSize(QtCore.QSize(150, 15))
        self.AnimalName.setObjectName("AnimalName")
        self.splitter_3 = QtGui.QSplitter(self.splitter_27)
        self.splitter_3.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.AnimalTypeLabel = QtGui.QLabel(self.splitter_3)
        self.AnimalTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AnimalTypeLabel.setObjectName("AnimalTypeLabel")
        self.OptionDog = QtGui.QRadioButton(self.splitter_3)
        self.OptionDog.setMinimumSize(QtCore.QSize(46, 15))
        self.OptionDog.setObjectName("OptionDog")
        self.OptionCat = QtGui.QRadioButton(self.splitter_3)
        self.OptionCat.setMinimumSize(QtCore.QSize(44, 15))
        self.OptionCat.setObjectName("OptionCat")
        self.OptionOther = QtGui.QRadioButton(self.splitter_3)
        self.OptionOther.setMinimumSize(QtCore.QSize(56, 15))
        self.OptionOther.setObjectName("OptionOther")
        self.splitter_4 = QtGui.QSplitter(self.splitter_27)
        self.splitter_4.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.AnimalAgeLabel = QtGui.QLabel(self.splitter_4)
        self.AnimalAgeLabel.setMinimumSize(QtCore.QSize(135, 15))
        self.AnimalAgeLabel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.AnimalAgeLabel.setObjectName("AnimalAgeLabel")
        self.AnimalAge = QtGui.QSpinBox(self.splitter_4)
        self.AnimalAge.setMinimumSize(QtCore.QSize(84, 15))
        self.AnimalAge.setObjectName("AnimalAge")
        self.splitter_2 = QtGui.QSplitter(self.splitter_27)
        self.splitter_2.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.DOBLabel = QtGui.QLabel(self.splitter_2)
        self.DOBLabel.setMinimumSize(QtCore.QSize(93, 15))
        self.DOBLabel.setObjectName("DOBLabel")
        self.DOB = QtGui.QDateEdit(self.splitter_2)
        self.DOB.setMinimumSize(QtCore.QSize(126, 15))
        self.DOB.setObjectName("DOB")
        self.splitter_5 = QtGui.QSplitter(self.splitter_27)
        self.splitter_5.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.DOALabel = QtGui.QLabel(self.splitter_5)
        self.DOALabel.setMinimumSize(QtCore.QSize(100, 15))
        self.DOALabel.setObjectName("DOALabel")
        self.DOA = QtGui.QDateEdit(self.splitter_5)
        self.DOA.setMinimumSize(QtCore.QSize(119, 15))
        self.DOA.setObjectName("DOA")
        self.splitter_7 = QtGui.QSplitter(self.splitter_27)
        self.splitter_7.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.MicroChippedLabel = QtGui.QLabel(self.splitter_7)
        self.MicroChippedLabel.setMinimumSize(QtCore.QSize(104, 15))
        self.MicroChippedLabel.setObjectName("MicroChippedLabel")
        self.OptionYes = QtGui.QRadioButton(self.splitter_7)
        self.OptionYes.setMinimumSize(QtCore.QSize(57, 15))
        self.OptionYes.setObjectName("OptionYes")
        self.OptionNo = QtGui.QRadioButton(self.splitter_7)
        self.OptionNo.setMinimumSize(QtCore.QSize(53, 15))
        self.OptionNo.setObjectName("OptionNo")
        self.splitter_8 = QtGui.QSplitter(self.splitter_27)
        self.splitter_8.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.GivingPartyLabel = QtGui.QLabel(self.splitter_8)
        self.GivingPartyLabel.setMinimumSize(QtCore.QSize(91, 15))
        self.GivingPartyLabel.setObjectName("GivingPartyLabel")
        self.GivingParty = QtGui.QLineEdit(self.splitter_8)
        self.GivingParty.setMinimumSize(QtCore.QSize(128, 15))
        self.GivingParty.setObjectName("GivingParty")
        self.splitter_9 = QtGui.QSplitter(self.splitter_27)
        self.splitter_9.setMinimumSize(QtCore.QSize(224, 14))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_9 = QtGui.QLabel(self.splitter_9)
        self.label_9.setMinimumSize(QtCore.QSize(145, 14))
        self.label_9.setObjectName("label_9")
        self.CageNumber = QtGui.QSpinBox(self.splitter_9)
        self.CageNumber.setMinimumSize(QtCore.QSize(74, 14))
        self.CageNumber.setObjectName("CageNumber")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 60, 341, 311))
        self.groupBox_2.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox1 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox1.setGeometry(QtCore.QRect(10, 10, 321, 291))
        self.groupBox1.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.toolButton_3 = QtGui.QToolButton(self.groupBox1)
        self.toolButton_3.setStyleSheet("selection-background-color: rgb(120, 0, 0);")
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_19.addWidget(self.toolButton_3)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QtGui.QLabel(self.groupBox1)
        self.label_2.setMinimumSize(QtCore.QSize(71, 16))
        self.label_2.setMaximumSize(QtCore.QSize(71, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox1)
        self.label_3.setMinimumSize(QtCore.QSize(47, 20))
        self.label_3.setMaximumSize(QtCore.QSize(48, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.DogWeight = QtGui.QSpinBox(self.groupBox1)
        self.DogWeight.setMaximumSize(QtCore.QSize(110, 20))
        self.DogWeight.setObjectName("DogWeight")
        self.verticalLayout_16.addWidget(self.DogWeight)
        self.lineEdit = QtGui.QLineEdit(self.groupBox1)
        self.lineEdit.setMinimumSize(QtCore.QSize(128, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(136, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_16.addWidget(self.lineEdit)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_4 = QtGui.QLabel(self.groupBox1)
        self.label_4.setMaximumSize(QtCore.QSize(58, 17))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox1)
        self.label_5.setMinimumSize(QtCore.QSize(35, 16))
        self.label_5.setMaximumSize(QtCore.QSize(189, 16))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox1)
        self.label_6.setMinimumSize(QtCore.QSize(85, 17))
        self.label_6.setMaximumSize(QtCore.QSize(85, 17))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox1)
        self.label_7.setMinimumSize(QtCore.QSize(36, 17))
        self.label_7.setMaximumSize(QtCore.QSize(50, 17))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox1)
        self.label_8.setMinimumSize(QtCore.QSize(55, 17))
        self.label_8.setMaximumSize(QtCore.QSize(80, 17))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton = QtGui.QRadioButton(self.groupBox1)
        self.radioButton.setMaximumSize(QtCore.QSize(59, 17))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_3.setMinimumSize(QtCore.QSize(45, 17))
        self.radioButton_3.setMaximumSize(QtCore.QSize(189, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_13.addWidget(self.radioButton_3)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_5.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_13.addWidget(self.radioButton_5)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_7.setMinimumSize(QtCore.QSize(51, 17))
        self.radioButton_7.setMaximumSize(QtCore.QSize(69, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_13.addWidget(self.radioButton_7)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_9.setMinimumSize(QtCore.QSize(42, 17))
        self.radioButton_9.setMaximumSize(QtCore.QSize(51, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_13.addWidget(self.radioButton_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_2.setMaximumSize(QtCore.QSize(58, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_5.addWidget(self.radioButton_2)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_4.setMinimumSize(QtCore.QSize(61, 17))
        self.radioButton_4.setMaximumSize(QtCore.QSize(189, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_5.addWidget(self.radioButton_4)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_6.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_5.addWidget(self.radioButton_6)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_8.setMinimumSize(QtCore.QSize(44, 17))
        self.radioButton_8.setMaximumSize(QtCore.QSize(60, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_5.addWidget(self.radioButton_8)
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox1)
        self.radioButton_10.setMinimumSize(QtCore.QSize(39, 17))
        self.radioButton_10.setMaximumSize(QtCore.QSize(48, 17))
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_5.addWidget(self.radioButton_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtGui.QLabel(self.groupBox1)
        self.label_10.setMinimumSize(QtCore.QSize(71, 17))
        self.label_10.setMaximumSize(QtCore.QSize(71, 17))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.checkBox = QtGui.QCheckBox(self.groupBox1)
        self.checkBox.setMinimumSize(QtCore.QSize(74, 17))
        self.checkBox.setMaximumSize(QtCore.QSize(110, 17))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox1)
        self.checkBox_3.setMinimumSize(QtCore.QSize(90, 17))
        self.checkBox_3.setMaximumSize(QtCore.QSize(90, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_6.addWidget(self.checkBox_3)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox1)
        self.checkBox_2.setMinimumSize(QtCore.QSize(91, 17))
        self.checkBox_2.setMaximumSize(QtCore.QSize(91, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_6)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 60, 272, 275))
        self.groupBox_3.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox4.setStyleSheet("background-color: rgb(94, 94, 94);")
        self.groupBox4.setObjectName("groupBox4")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.toolButton_2 = QtGui.QToolButton(self.groupBox4)
        self.toolButton_2.setObjectName("toolButton_2")
        self.verticalLayout_12.addWidget(self.toolButton_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtGui.QLabel(self.groupBox4)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        self.label_16.setMaximumSize(QtCore.QSize(102, 20))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.label_14 = QtGui.QLabel(self.groupBox4)
        self.label_14.setMinimumSize(QtCore.QSize(47, 20))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.DogWeight_2 = QtGui.QSpinBox(self.groupBox4)
        self.DogWeight_2.setMinimumSize(QtCore.QSize(86, 20))
        self.DogWeight_2.setMaximumSize(QtCore.QSize(101, 20))
        self.DogWeight_2.setObjectName("DogWeight_2")
        self.verticalLayout_10.addWidget(self.DogWeight_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox4)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(128, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(152, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_13 = QtGui.QLabel(self.groupBox4)
        self.label_13.setMinimumSize(QtCore.QSize(58, 19))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtGui.QLabel(self.groupBox4)
        self.label_12.setMinimumSize(QtCore.QSize(44, 17))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.label_17 = QtGui.QLabel(self.groupBox4)
        self.label_17.setMinimumSize(QtCore.QSize(91, 17))
        self.label_17.setMaximumSize(QtCore.QSize(107, 17))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_15 = QtGui.QLabel(self.groupBox4)
        self.label_15.setMinimumSize(QtCore.QSize(36, 17))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_18 = QtGui.QLabel(self.groupBox4)
        self.label_18.setMinimumSize(QtCore.QSize(64, 17))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.groupBox4)
        self.label_19.setMinimumSize(QtCore.QSize(70, 20))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_13.setMinimumSize(QtCore.QSize(0, 19))
        self.radioButton_13.setMaximumSize(QtCore.QSize(65, 19))
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_6.addWidget(self.radioButton_13)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_11.setMinimumSize(QtCore.QSize(56, 17))
        self.radioButton_11.setMaximumSize(QtCore.QSize(66, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_6.addWidget(self.radioButton_11)
        self.radioButton_17 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_17.setMinimumSize(QtCore.QSize(42, 17))
        self.radioButton_17.setMaximumSize(QtCore.QSize(49, 17))
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout_6.addWidget(self.radioButton_17)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_15.setMinimumSize(QtCore.QSize(51, 17))
        self.radioButton_15.setMaximumSize(QtCore.QSize(78, 17))
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_6.addWidget(self.radioButton_15)
        self.radioButton_19 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_19.setMinimumSize(QtCore.QSize(52, 17))
        self.radioButton_19.setMaximumSize(QtCore.QSize(66, 17))
        self.radioButton_19.setObjectName("radioButton_19")
        self.verticalLayout_6.addWidget(self.radioButton_19)
        self.radioButton_21 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_21.setMinimumSize(QtCore.QSize(62, 20))
        self.radioButton_21.setMaximumSize(QtCore.QSize(62, 20))
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_6.addWidget(self.radioButton_21)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_14.setMinimumSize(QtCore.QSize(0, 19))
        self.radioButton_14.setMaximumSize(QtCore.QSize(66, 19))
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout.addWidget(self.radioButton_14)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_12.setMinimumSize(QtCore.QSize(71, 17))
        self.radioButton_12.setMaximumSize(QtCore.QSize(84, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout.addWidget(self.radioButton_12)
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_18.setMinimumSize(QtCore.QSize(38, 17))
        self.radioButton_18.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout.addWidget(self.radioButton_18)
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_16.setMinimumSize(QtCore.QSize(44, 17))
        self.radioButton_16.setMaximumSize(QtCore.QSize(67, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout.addWidget(self.radioButton_16)
        self.radioButton_20 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_20.setMinimumSize(QtCore.QSize(45, 17))
        self.radioButton_20.setMaximumSize(QtCore.QSize(56, 17))
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout.addWidget(self.radioButton_20)
        self.radioButton_22 = QtGui.QRadioButton(self.groupBox4)
        self.radioButton_22.setMinimumSize(QtCore.QSize(69, 20))
        self.radioButton_22.setMaximumSize(QtCore.QSize(69, 20))
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout.addWidget(self.radioButton_22)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.splitter_26 = QtGui.QSplitter(self.groupBox4)
        self.splitter_26.setMinimumSize(QtCore.QSize(0, 17))
        self.splitter_26.setMaximumSize(QtCore.QSize(211, 17))
        self.splitter_26.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_26.setObjectName("splitter_26")
        self.label_20 = QtGui.QLabel(self.splitter_26)
        self.label_20.setMinimumSize(QtCore.QSize(0, 17))
        self.label_20.setMaximumSize(QtCore.QSize(103, 17))
        self.label_20.setObjectName("label_20")
        self.checkBox_4 = QtGui.QCheckBox(self.splitter_26)
        self.checkBox_4.setMinimumSize(QtCore.QSize(0, 17))
        self.checkBox_4.setMaximumSize(QtCore.QSize(103, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_12.addWidget(self.splitter_26)
        self.gridLayout_2.addWidget(self.groupBox4, 0, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(-10, -80, 564, 498))
        self.tabWidget_2.setStyleSheet("background-color: rgb(58, 58, 58);\n"
"font: 8pt \"Arial\";")
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 60, 371, 301))
        self.groupBox_5.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.splitter_28 = QtGui.QSplitter(self.groupBox_5)
        self.splitter_28.setGeometry(QtCore.QRect(10, 10, 310, 250))
        self.splitter_28.setMinimumSize(QtCore.QSize(224, 174))
        self.splitter_28.setOrientation(QtCore.Qt.Vertical)
        self.splitter_28.setObjectName("splitter_28")
        self.splitter_10 = QtGui.QSplitter(self.splitter_28)
        self.splitter_10.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.CaseNumberLabel_2 = QtGui.QLabel(self.splitter_10)
        self.CaseNumberLabel_2.setObjectName("CaseNumberLabel_2")
        self.CaseNumber_2 = QtGui.QLineEdit(self.splitter_10)
        self.CaseNumber_2.setMinimumSize(QtCore.QSize(148, 15))
        self.CaseNumber_2.setObjectName("CaseNumber_2")
        self.splitter_11 = QtGui.QSplitter(self.splitter_28)
        self.splitter_11.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.AnimalNameLabel_2 = QtGui.QLabel(self.splitter_11)
        self.AnimalNameLabel_2.setObjectName("AnimalNameLabel_2")
        self.AnimalName_2 = QtGui.QLineEdit(self.splitter_11)
        self.AnimalName_2.setMinimumSize(QtCore.QSize(150, 15))
        self.AnimalName_2.setObjectName("AnimalName_2")
        self.splitter_12 = QtGui.QSplitter(self.splitter_28)
        self.splitter_12.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.AnimalTypeLabel_2 = QtGui.QLabel(self.splitter_12)
        self.AnimalTypeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.AnimalTypeLabel_2.setObjectName("AnimalTypeLabel_2")
        self.OptionDog_2 = QtGui.QRadioButton(self.splitter_12)
        self.OptionDog_2.setMinimumSize(QtCore.QSize(46, 15))
        self.OptionDog_2.setObjectName("OptionDog_2")
        self.OptionCat_2 = QtGui.QRadioButton(self.splitter_12)
        self.OptionCat_2.setMinimumSize(QtCore.QSize(44, 15))
        self.OptionCat_2.setObjectName("OptionCat_2")
        self.OptionOther_2 = QtGui.QRadioButton(self.splitter_12)
        self.OptionOther_2.setMinimumSize(QtCore.QSize(56, 15))
        self.OptionOther_2.setObjectName("OptionOther_2")
        self.splitter_13 = QtGui.QSplitter(self.splitter_28)
        self.splitter_13.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.AnimalAgeLabel_2 = QtGui.QLabel(self.splitter_13)
        self.AnimalAgeLabel_2.setMinimumSize(QtCore.QSize(135, 15))
        self.AnimalAgeLabel_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.AnimalAgeLabel_2.setObjectName("AnimalAgeLabel_2")
        self.AnimalAge_2 = QtGui.QSpinBox(self.splitter_13)
        self.AnimalAge_2.setMinimumSize(QtCore.QSize(84, 15))
        self.AnimalAge_2.setObjectName("AnimalAge_2")
        self.splitter_14 = QtGui.QSplitter(self.splitter_28)
        self.splitter_14.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.DOBLabel_2 = QtGui.QLabel(self.splitter_14)
        self.DOBLabel_2.setMinimumSize(QtCore.QSize(93, 15))
        self.DOBLabel_2.setObjectName("DOBLabel_2")
        self.DOB_2 = QtGui.QDateEdit(self.splitter_14)
        self.DOB_2.setMinimumSize(QtCore.QSize(126, 15))
        self.DOB_2.setObjectName("DOB_2")
        self.splitter_15 = QtGui.QSplitter(self.splitter_28)
        self.splitter_15.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.DOALabel_2 = QtGui.QLabel(self.splitter_15)
        self.DOALabel_2.setMinimumSize(QtCore.QSize(100, 15))
        self.DOALabel_2.setObjectName("DOALabel_2")
        self.DOA_2 = QtGui.QDateEdit(self.splitter_15)
        self.DOA_2.setMinimumSize(QtCore.QSize(119, 15))
        self.DOA_2.setObjectName("DOA_2")
        self.splitter_16 = QtGui.QSplitter(self.splitter_28)
        self.splitter_16.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.MicroChippedLabel_2 = QtGui.QLabel(self.splitter_16)
        self.MicroChippedLabel_2.setMinimumSize(QtCore.QSize(104, 15))
        self.MicroChippedLabel_2.setObjectName("MicroChippedLabel_2")
        self.OptionYes_2 = QtGui.QRadioButton(self.splitter_16)
        self.OptionYes_2.setMinimumSize(QtCore.QSize(57, 15))
        self.OptionYes_2.setObjectName("OptionYes_2")
        self.OptionNo_2 = QtGui.QRadioButton(self.splitter_16)
        self.OptionNo_2.setMinimumSize(QtCore.QSize(53, 15))
        self.OptionNo_2.setObjectName("OptionNo_2")
        self.splitter_17 = QtGui.QSplitter(self.splitter_28)
        self.splitter_17.setMinimumSize(QtCore.QSize(224, 15))
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.GivingPartyLabel_2 = QtGui.QLabel(self.splitter_17)
        self.GivingPartyLabel_2.setMinimumSize(QtCore.QSize(91, 15))
        self.GivingPartyLabel_2.setObjectName("GivingPartyLabel_2")
        self.GivingParty_2 = QtGui.QLineEdit(self.splitter_17)
        self.GivingParty_2.setMinimumSize(QtCore.QSize(128, 15))
        self.GivingParty_2.setObjectName("GivingParty_2")
        self.splitter_18 = QtGui.QSplitter(self.splitter_28)
        self.splitter_18.setMinimumSize(QtCore.QSize(224, 14))
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.label_11 = QtGui.QLabel(self.splitter_18)
        self.label_11.setMinimumSize(QtCore.QSize(145, 14))
        self.label_11.setObjectName("label_11")
        self.CageNumber_2 = QtGui.QSpinBox(self.splitter_18)
        self.CageNumber_2.setMinimumSize(QtCore.QSize(74, 14))
        self.CageNumber_2.setObjectName("CageNumber_2")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 60, 341, 311))
        self.groupBox_6.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 321, 291))
        self.groupBox_7.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.toolButton_4 = QtGui.QToolButton(self.groupBox_7)
        self.toolButton_4.setStyleSheet("selection-background-color: rgb(120, 0, 0);")
        self.toolButton_4.setObjectName("toolButton_4")
        self.verticalLayout_22.addWidget(self.toolButton_4)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setMinimumSize(QtCore.QSize(71, 16))
        self.label_21.setMaximumSize(QtCore.QSize(71, 20))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_24.addWidget(self.label_21)
        self.label_27 = QtGui.QLabel(self.groupBox_7)
        self.label_27.setMinimumSize(QtCore.QSize(47, 20))
        self.label_27.setMaximumSize(QtCore.QSize(48, 20))
        self.label_27.setObjectName("label_27")
        self.verticalLayout_24.addWidget(self.label_27)
        self.horizontalLayout_10.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.DogWeight_3 = QtGui.QSpinBox(self.groupBox_7)
        self.DogWeight_3.setMaximumSize(QtCore.QSize(110, 20))
        self.DogWeight_3.setObjectName("DogWeight_3")
        self.verticalLayout_25.addWidget(self.DogWeight_3)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(128, 20))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(136, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_25.addWidget(self.lineEdit_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_25)
        self.verticalLayout_23.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setMaximumSize(QtCore.QSize(58, 17))
        self.label_28.setObjectName("label_28")
        self.verticalLayout_26.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setMinimumSize(QtCore.QSize(35, 16))
        self.label_29.setMaximumSize(QtCore.QSize(189, 16))
        self.label_29.setObjectName("label_29")
        self.verticalLayout_26.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setMinimumSize(QtCore.QSize(85, 17))
        self.label_30.setMaximumSize(QtCore.QSize(85, 17))
        self.label_30.setObjectName("label_30")
        self.verticalLayout_26.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.groupBox_7)
        self.label_31.setMinimumSize(QtCore.QSize(36, 17))
        self.label_31.setMaximumSize(QtCore.QSize(50, 17))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_26.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.groupBox_7)
        self.label_32.setMinimumSize(QtCore.QSize(55, 17))
        self.label_32.setMaximumSize(QtCore.QSize(80, 17))
        self.label_32.setObjectName("label_32")
        self.verticalLayout_26.addWidget(self.label_32)
        self.horizontalLayout_11.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.radioButton_23 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_23.setMaximumSize(QtCore.QSize(59, 17))
        self.radioButton_23.setObjectName("radioButton_23")
        self.verticalLayout_27.addWidget(self.radioButton_23)
        self.radioButton_24 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_24.setMinimumSize(QtCore.QSize(45, 17))
        self.radioButton_24.setMaximumSize(QtCore.QSize(189, 17))
        self.radioButton_24.setObjectName("radioButton_24")
        self.verticalLayout_27.addWidget(self.radioButton_24)
        self.radioButton_25 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_25.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_25.setObjectName("radioButton_25")
        self.verticalLayout_27.addWidget(self.radioButton_25)
        self.radioButton_26 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_26.setMinimumSize(QtCore.QSize(51, 17))
        self.radioButton_26.setMaximumSize(QtCore.QSize(69, 17))
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_27.addWidget(self.radioButton_26)
        self.radioButton_27 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_27.setMinimumSize(QtCore.QSize(42, 17))
        self.radioButton_27.setMaximumSize(QtCore.QSize(51, 17))
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_27.addWidget(self.radioButton_27)
        self.horizontalLayout_11.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.radioButton_28 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_28.setMaximumSize(QtCore.QSize(58, 17))
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_28.addWidget(self.radioButton_28)
        self.radioButton_29 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_29.setMinimumSize(QtCore.QSize(61, 17))
        self.radioButton_29.setMaximumSize(QtCore.QSize(189, 17))
        self.radioButton_29.setObjectName("radioButton_29")
        self.verticalLayout_28.addWidget(self.radioButton_29)
        self.radioButton_30 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_30.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_28.addWidget(self.radioButton_30)
        self.radioButton_31 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_31.setMinimumSize(QtCore.QSize(44, 17))
        self.radioButton_31.setMaximumSize(QtCore.QSize(60, 17))
        self.radioButton_31.setObjectName("radioButton_31")
        self.verticalLayout_28.addWidget(self.radioButton_31)
        self.radioButton_32 = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_32.setMinimumSize(QtCore.QSize(39, 17))
        self.radioButton_32.setMaximumSize(QtCore.QSize(48, 17))
        self.radioButton_32.setObjectName("radioButton_32")
        self.verticalLayout_28.addWidget(self.radioButton_32)
        self.horizontalLayout_11.addLayout(self.verticalLayout_28)
        self.verticalLayout_23.addLayout(self.horizontalLayout_11)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_33 = QtGui.QLabel(self.groupBox_7)
        self.label_33.setMinimumSize(QtCore.QSize(71, 17))
        self.label_33.setMaximumSize(QtCore.QSize(71, 17))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_5.setMinimumSize(QtCore.QSize(74, 17))
        self.checkBox_5.setMaximumSize(QtCore.QSize(110, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_12.addWidget(self.checkBox_5)
        self.verticalLayout_29.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_6.setMinimumSize(QtCore.QSize(90, 17))
        self.checkBox_6.setMaximumSize(QtCore.QSize(90, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_13.addWidget(self.checkBox_6)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_7.setMinimumSize(QtCore.QSize(91, 17))
        self.checkBox_7.setMaximumSize(QtCore.QSize(91, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_13.addWidget(self.checkBox_7)
        self.verticalLayout_29.addLayout(self.horizontalLayout_13)
        self.verticalLayout_23.addLayout(self.verticalLayout_29)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_8 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 60, 272, 275))
        self.groupBox_8.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox4_2 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox4_2.setStyleSheet("background-color: rgb(94, 94, 94);")
        self.groupBox4_2.setObjectName("groupBox4_2")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.groupBox4_2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.toolButton_5 = QtGui.QToolButton(self.groupBox4_2)
        self.toolButton_5.setObjectName("toolButton_5")
        self.verticalLayout_30.addWidget(self.toolButton_5)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_34 = QtGui.QLabel(self.groupBox4_2)
        self.label_34.setMinimumSize(QtCore.QSize(0, 20))
        self.label_34.setMaximumSize(QtCore.QSize(102, 20))
        self.label_34.setObjectName("label_34")
        self.verticalLayout_31.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.groupBox4_2)
        self.label_35.setMinimumSize(QtCore.QSize(47, 20))
        self.label_35.setObjectName("label_35")
        self.verticalLayout_31.addWidget(self.label_35)
        self.horizontalLayout_14.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.DogWeight_4 = QtGui.QSpinBox(self.groupBox4_2)
        self.DogWeight_4.setMinimumSize(QtCore.QSize(86, 20))
        self.DogWeight_4.setMaximumSize(QtCore.QSize(101, 20))
        self.DogWeight_4.setObjectName("DogWeight_4")
        self.verticalLayout_32.addWidget(self.DogWeight_4)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox4_2)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(128, 20))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(152, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_32.addWidget(self.lineEdit_8)
        self.horizontalLayout_14.addLayout(self.verticalLayout_32)
        self.verticalLayout_30.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_36 = QtGui.QLabel(self.groupBox4_2)
        self.label_36.setMinimumSize(QtCore.QSize(58, 19))
        self.label_36.setObjectName("label_36")
        self.verticalLayout_33.addWidget(self.label_36)
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_37 = QtGui.QLabel(self.groupBox4_2)
        self.label_37.setMinimumSize(QtCore.QSize(44, 17))
        self.label_37.setObjectName("label_37")
        self.verticalLayout_34.addWidget(self.label_37)
        self.label_38 = QtGui.QLabel(self.groupBox4_2)
        self.label_38.setMinimumSize(QtCore.QSize(91, 17))
        self.label_38.setMaximumSize(QtCore.QSize(107, 17))
        self.label_38.setObjectName("label_38")
        self.verticalLayout_34.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.groupBox4_2)
        self.label_39.setMinimumSize(QtCore.QSize(36, 17))
        self.label_39.setObjectName("label_39")
        self.verticalLayout_34.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.groupBox4_2)
        self.label_40.setMinimumSize(QtCore.QSize(64, 17))
        self.label_40.setObjectName("label_40")
        self.verticalLayout_34.addWidget(self.label_40)
        self.label_41 = QtGui.QLabel(self.groupBox4_2)
        self.label_41.setMinimumSize(QtCore.QSize(70, 20))
        self.label_41.setObjectName("label_41")
        self.verticalLayout_34.addWidget(self.label_41)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.horizontalLayout_15.addLayout(self.verticalLayout_33)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.radioButton_33 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_33.setMinimumSize(QtCore.QSize(0, 19))
        self.radioButton_33.setMaximumSize(QtCore.QSize(65, 19))
        self.radioButton_33.setObjectName("radioButton_33")
        self.verticalLayout_36.addWidget(self.radioButton_33)
        self.radioButton_34 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_34.setMinimumSize(QtCore.QSize(56, 17))
        self.radioButton_34.setMaximumSize(QtCore.QSize(66, 17))
        self.radioButton_34.setObjectName("radioButton_34")
        self.verticalLayout_36.addWidget(self.radioButton_34)
        self.radioButton_35 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_35.setMinimumSize(QtCore.QSize(42, 17))
        self.radioButton_35.setMaximumSize(QtCore.QSize(49, 17))
        self.radioButton_35.setObjectName("radioButton_35")
        self.verticalLayout_36.addWidget(self.radioButton_35)
        self.radioButton_36 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_36.setMinimumSize(QtCore.QSize(51, 17))
        self.radioButton_36.setMaximumSize(QtCore.QSize(78, 17))
        self.radioButton_36.setObjectName("radioButton_36")
        self.verticalLayout_36.addWidget(self.radioButton_36)
        self.radioButton_37 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_37.setMinimumSize(QtCore.QSize(52, 17))
        self.radioButton_37.setMaximumSize(QtCore.QSize(66, 17))
        self.radioButton_37.setObjectName("radioButton_37")
        self.verticalLayout_36.addWidget(self.radioButton_37)
        self.radioButton_38 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_38.setMinimumSize(QtCore.QSize(62, 20))
        self.radioButton_38.setMaximumSize(QtCore.QSize(62, 20))
        self.radioButton_38.setObjectName("radioButton_38")
        self.verticalLayout_36.addWidget(self.radioButton_38)
        self.verticalLayout_35.addLayout(self.verticalLayout_36)
        self.horizontalLayout_15.addLayout(self.verticalLayout_35)
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.radioButton_39 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_39.setMinimumSize(QtCore.QSize(0, 19))
        self.radioButton_39.setMaximumSize(QtCore.QSize(66, 19))
        self.radioButton_39.setObjectName("radioButton_39")
        self.verticalLayout_37.addWidget(self.radioButton_39)
        self.radioButton_40 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_40.setMinimumSize(QtCore.QSize(71, 17))
        self.radioButton_40.setMaximumSize(QtCore.QSize(84, 17))
        self.radioButton_40.setObjectName("radioButton_40")
        self.verticalLayout_37.addWidget(self.radioButton_40)
        self.radioButton_41 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_41.setMinimumSize(QtCore.QSize(38, 17))
        self.radioButton_41.setMaximumSize(QtCore.QSize(45, 17))
        self.radioButton_41.setObjectName("radioButton_41")
        self.verticalLayout_37.addWidget(self.radioButton_41)
        self.radioButton_42 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_42.setMinimumSize(QtCore.QSize(44, 17))
        self.radioButton_42.setMaximumSize(QtCore.QSize(67, 17))
        self.radioButton_42.setObjectName("radioButton_42")
        self.verticalLayout_37.addWidget(self.radioButton_42)
        self.radioButton_43 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_43.setMinimumSize(QtCore.QSize(45, 17))
        self.radioButton_43.setMaximumSize(QtCore.QSize(56, 17))
        self.radioButton_43.setObjectName("radioButton_43")
        self.verticalLayout_37.addWidget(self.radioButton_43)
        self.radioButton_44 = QtGui.QRadioButton(self.groupBox4_2)
        self.radioButton_44.setMinimumSize(QtCore.QSize(69, 20))
        self.radioButton_44.setMaximumSize(QtCore.QSize(69, 20))
        self.radioButton_44.setObjectName("radioButton_44")
        self.verticalLayout_37.addWidget(self.radioButton_44)
        self.horizontalLayout_15.addLayout(self.verticalLayout_37)
        self.verticalLayout_30.addLayout(self.horizontalLayout_15)
        self.splitter_29 = QtGui.QSplitter(self.groupBox4_2)
        self.splitter_29.setMinimumSize(QtCore.QSize(0, 17))
        self.splitter_29.setMaximumSize(QtCore.QSize(211, 17))
        self.splitter_29.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_29.setObjectName("splitter_29")
        self.label_42 = QtGui.QLabel(self.splitter_29)
        self.label_42.setMinimumSize(QtCore.QSize(0, 17))
        self.label_42.setMaximumSize(QtCore.QSize(103, 17))
        self.label_42.setObjectName("label_42")
        self.checkBox_8 = QtGui.QCheckBox(self.splitter_29)
        self.checkBox_8.setMinimumSize(QtCore.QSize(0, 17))
        self.checkBox_8.setMaximumSize(QtCore.QSize(103, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_30.addWidget(self.splitter_29)
        self.gridLayout_4.addWidget(self.groupBox4_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_9 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_9.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 241, 399))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.toolButton_6 = QtGui.QToolButton(self.layoutWidget_2)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_38.addWidget(self.toolButton_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_43 = QtGui.QLabel(self.layoutWidget_2)
        self.label_43.setMinimumSize(QtCore.QSize(57, 20))
        self.label_43.setObjectName("label_43")
        self.verticalLayout_39.addWidget(self.label_43)
        self.label_44 = QtGui.QLabel(self.layoutWidget_2)
        self.label_44.setMinimumSize(QtCore.QSize(1, 1))
        self.label_44.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_44.setObjectName("label_44")
        self.verticalLayout_39.addWidget(self.label_44)
        self.label_45 = QtGui.QLabel(self.layoutWidget_2)
        self.label_45.setMinimumSize(QtCore.QSize(58, 20))
        self.label_45.setObjectName("label_45")
        self.verticalLayout_39.addWidget(self.label_45)
        self.horizontalLayout_2.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtGui.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(1, 1))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_40.addWidget(self.lineEdit_9)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinBox_2.setMinimumSize(QtCore.QSize(98, 20))
        self.spinBox_2.setMaximumSize(QtCore.QSize(98, 20))
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_40.addWidget(self.spinBox_2)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(1, 1))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_40.addWidget(self.lineEdit_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_40)
        self.verticalLayout_38.addLayout(self.horizontalLayout_2)
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_46 = QtGui.QLabel(self.layoutWidget_2)
        self.label_46.setMinimumSize(QtCore.QSize(201, 13))
        self.label_46.setMaximumSize(QtCore.QSize(201, 13))
        self.label_46.setObjectName("label_46")
        self.verticalLayout_41.addWidget(self.label_46)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(201, 121))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(201, 121))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_41.addWidget(self.lineEdit_11)
        self.verticalLayout_38.addLayout(self.verticalLayout_41)
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_47 = QtGui.QLabel(self.layoutWidget_2)
        self.label_47.setMinimumSize(QtCore.QSize(203, 13))
        self.label_47.setMaximumSize(QtCore.QSize(203, 13))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_42.addWidget(self.label_47)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(203, 121))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(203, 121))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_42.addWidget(self.lineEdit_12)
        self.verticalLayout_38.addLayout(self.verticalLayout_42)
        self.gridLayout_5.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 399))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.toolButton = QtGui.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_21.addWidget(self.toolButton)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setMinimumSize(QtCore.QSize(57, 20))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_20.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setMinimumSize(QtCore.QSize(1, 1))
        self.label_23.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_20.addWidget(self.label_23)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setMinimumSize(QtCore.QSize(58, 20))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_20.addWidget(self.label_25)
        self.horizontalLayout.addLayout(self.verticalLayout_20)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(1, 1))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(98, 20))
        self.spinBox.setMaximumSize(QtCore.QSize(98, 20))
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_4.addWidget(self.spinBox)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(1, 1))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_21.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setMinimumSize(QtCore.QSize(201, 13))
        self.label_26.setMaximumSize(QtCore.QSize(201, 13))
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(201, 121))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(201, 121))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.verticalLayout_21.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setMinimumSize(QtCore.QSize(203, 13))
        self.label_24.setMaximumSize(QtCore.QSize(203, 13))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(203, 121))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(203, 121))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.verticalLayout_21.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.CaseNumberLabel.setText(QtGui.QApplication.translate("MainWindow", "Case Number", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Animal Name", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "Animal Type", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionDog.setText(QtGui.QApplication.translate("MainWindow", "Dog", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionCat.setText(QtGui.QApplication.translate("MainWindow", "Cat", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionOther.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalAgeLabel.setText(QtGui.QApplication.translate("MainWindow", "Animal Age", None, QtGui.QApplication.UnicodeUTF8))
        self.DOBLabel.setText(QtGui.QApplication.translate("MainWindow", "Date of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.DOALabel.setText(QtGui.QApplication.translate("MainWindow", "Date of Arrival", None, QtGui.QApplication.UnicodeUTF8))
        self.MicroChippedLabel.setText(QtGui.QApplication.translate("MainWindow", "Micro-chipped?", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionYes.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionNo.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.GivingPartyLabel.setText(QtGui.QApplication.translate("MainWindow", "Relinquishing Party", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Cage Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Basic Information", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "Dogs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Hair Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Type of Hair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Spayed/Neutered", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Fleas?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "HeartWorms?", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("MainWindow", " No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "  Rabies", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", " Bordetella", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", " Distemper", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Dog Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "Cats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Hair Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Type of Hair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Spayed/Neutered", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Fleas?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Declawed?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Leukemia Test", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_13.setText(QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_17.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_19.setText(QtGui.QApplication.translate("MainWindow", "Yes ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_21.setText(QtGui.QApplication.translate("MainWindow", "Positive", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_14.setText(QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_18.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_16.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_20.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_22.setText(QtGui.QApplication.translate("MainWindow", "Negative", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", " Rabies", None, QtGui.QApplication.UnicodeUTF8))
        self.CaseNumberLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Case Number", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalNameLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Animal Name", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalTypeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Animal Type", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionDog_2.setText(QtGui.QApplication.translate("MainWindow", "Dog", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionCat_2.setText(QtGui.QApplication.translate("MainWindow", "Cat", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionOther_2.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.AnimalAgeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Animal Age", None, QtGui.QApplication.UnicodeUTF8))
        self.DOBLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Date of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.DOALabel_2.setText(QtGui.QApplication.translate("MainWindow", "Date of Arrival", None, QtGui.QApplication.UnicodeUTF8))
        self.MicroChippedLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Micro-chipped?", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionYes_2.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionNo_2.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.GivingPartyLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Relinquishing Party", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Cage Number", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Basic Information", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "Dogs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Hair Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Type of Hair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Spayed/Neutered", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Fleas?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "HeartWorms?", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_23.setText(QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_24.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_25.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_26.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_27.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_28.setText(QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_29.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_30.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_31.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_32.setText(QtGui.QApplication.translate("MainWindow", " No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "  Rabies", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", " Bordetella", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", " Distemper", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Dog Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "Cats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Hair Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Type of Hair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Spayed/Neutered", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Fleas?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Declawed?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Leukemia Test", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_33.setText(QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_34.setText(QtGui.QApplication.translate("MainWindow", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_35.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_36.setText(QtGui.QApplication.translate("MainWindow", " Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_37.setText(QtGui.QApplication.translate("MainWindow", "Yes ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_38.setText(QtGui.QApplication.translate("MainWindow", "Positive", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_39.setText(QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_40.setText(QtGui.QApplication.translate("MainWindow", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_41.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_42.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_43.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_44.setText(QtGui.QApplication.translate("MainWindow", "Negative", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow", " Rabies", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Cat Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Animal Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "General Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Animal Appearance Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Misc. Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Cat Entries", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Animal Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Vaccinations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "General Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Animal Appearance Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Misc. Entries", None, QtGui.QApplication.UnicodeUTF8))

